### ISSUE TITLE
add a block for appeals_court 

### ISSUE THREAD

**Issue by aubsticle** [SuffolkLITLab/docassemble-MassAppealsCourt#7]
I got an error when I ran my package from the Weaver. The error stated 

```
"Interview has an error. There was a reference to a variable 'appeals_court' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file." 
``` 

`'appeals_court'` is in the [next_steps_appeal.docx ](https://github.com/SuffolkLITLab/docassemble-ALWeaver/blob/main/docassemble/ALWeaver/data/templates/next_steps_appeal.docx) template in the ALWeaver package.   

We need to add a block in the appeals-basic-questions.yml to define `appeals_court`.  Appeals court information for MA found in the MACourts package, [appeals_court.json](https://github.com/GBLS/docassemble-MACourts/blob/master/docassemble/MACourts/data/sources/appeals_court.json)

**Comment by nonprofittechy** [comment]
I have an open issue for that here: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/issues/144

I can move it up in priority

**Comment by aubsticle** [comment]
proposed solution - tested in [appeals brief template ](https://github.com/stevejaubz/docassemble-AppealsBriefTemplate)

```yml
---
code: | 
  appeals_court = macourts.matching_appeals_court("")
---
modules:
  - docassemble.MACourts.macourts
---
objects:
  - macourts: MACourtList.using(courts=['appeals_court'])  # this is for lookups
```
